version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
      - "4455:4455"
    environment:
      PRISMA_CONFIG: |
        port: 4455
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-3-237-55-96.compute-1.amazonaws.com
            port: '5432'
            database: d5tggaet6rd26a
            ssl: true
            user: gbdddmzrvuawji
            password: f24be63e1da4a44ea42fab1bff41830c88a0c7c70a48143befbd4f6657c9644c
            migrations: true
